--------------------------------------------------------
--  DDL for Table GWIS_TL_COUNTIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_TL_COUNTIES" 
   (	"COUNTY_CODE" NUMBER(2,0) CONSTRAINT pk_upd_gwis_tl_counties PRIMARY KEY, 
	"COUNTY_NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_TL_COUNTIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_LAND_USE
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_TL_LAND_USE" 
   (	"LANDUSE_CODE" VARCHAR2(10 BYTE) CONSTRAINT pk_upd_gwis_tl_land_use PRIMARY KEY, 
	"LANDUSE_DESC" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_TL_LAND_USE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_SOURCES
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_TL_SOURCES" 
   (	"SOURCE_ID" NUMBER(10,0) CONSTRAINT pk_upd_gwis_tl_sources PRIMARY KEY, 
	"SOURCE_TYPE" VARCHAR2(2 BYTE), 
	"SOURCE_NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_TL_SOURCES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_DATA_INDEX
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_DATA_INDEX" 
   (	"GWTID" NUMBER(*,0) CONSTRAINT pk_upd_gwis_data_index PRIMARY KEY, 
	"SOURCE_DB" CHAR(5 BYTE), 
	"SITE_ORIGIN" CHAR(9 BYTE), 
	"SITE" VARCHAR2(70 BYTE), 
	"STATION_ORIGIN" CHAR(9 BYTE), 
	"STATION" NVARCHAR2(20), 
	"FAC_NAME" VARCHAR2(100 BYTE), 
	"DATA_TYPE" VARCHAR2(30 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_DATA_INDEX" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_GWTID_INFO
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_GWTID_INFO" 
   (	"GWTID" NUMBER(*,0) CONSTRAINT pk_upd_gwis_gwtid_info PRIMARY KEY, 
	"DATA_SOURCE" NUMBER(*,0), 
	"DATA_TYPE" VARCHAR2(10 BYTE), 
	"SITEID_2D" NUMBER(*,0), 
	"SITEID_3D" NUMBER(*,0),
    CONSTRAINT fk_upd_gwis_gwtid_info FOREIGN KEY (GWTID)
        REFERENCES "WSUP"."UPD_GWIS_DATA_INDEX"("GWTID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_GWTID_INFO" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_SITES_2D
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_SITES_2D" 
   (	"GWTID" NUMBER(*,0) CONSTRAINT upd_gwis_sites_2d PRIMARY KEY, 
	"STATION_NAME" VARCHAR2(20 BYTE),
    CONSTRAINT fk_upd_gwis_sites_2d_gwtid FOREIGN KEY (GWTID)
        REFERENCES "WSUP"."UPD_GWIS_DATA_INDEX"("GWTID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_SITES_2D" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_PERMIT_INFO
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_PERMIT_INFO" 
   (	"PERMIT_NO" VARCHAR2(70 BYTE), 
	"PROJECT_NAME" VARCHAR2(128 BYTE), 
	"APP_NO" VARCHAR2(15 BYTE) CONSTRAINT pk_upd_gwis_permit_info PRIMARY KEY, 
	"FINAL_ACTION_DATE" DATE, 
	"EXPIRATION_DATE" DATE, 
	"PERMIT_DURATION" VARCHAR2(26 BYTE), 
	"ACRES_SERVED" VARCHAR2(26 BYTE), 
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"FEE_CATEGORY" VARCHAR2(26 BYTE),
    CONSTRAINT fk_upd_gwis_permit_info_landuse_code FOREIGN KEY (LANDUSE_CODE)
        REFERENCES "WSUP"."UPD_GWIS_TL_LAND_USE"("LANDUSE_CODE")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_PERMIT_INFO" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_AG_IRR_ACRES
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_AG_IRR_ACRES" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"FIELD_ID" NUMBER(*,0), 
	"IRR_EFF" NUMBER(10,5), 
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"FIELD_ACRES" NUMBER(10,5), 
	"CROP_NAME" VARCHAR2(26 BYTE), 
	"USE_PRIORITY" NUMBER(*,0), 
	"IRR_TYPE" VARCHAR2(50 BYTE),
    CONSTRAINT fk_upd_gwis_ag_irr_acres_landuse_code FOREIGN KEY (LANDUSE_CODE)
        REFERENCES "WSUP"."UPD_GWIS_TL_LAND_USE"("LANDUSE_CODE")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_AG_IRR_ACRES" TO "PUB";
  GRANT READ ON "WSUP"."UPD_GWIS_AG_IRR_ACRES" TO "PUB";
  GRANT SELECT ON "WSUP"."UPD_GWIS_AG_IRR_ACRES" TO PUBLIC;
  GRANT READ ON "WSUP"."UPD_GWIS_AG_IRR_ACRES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_APP_COUNTIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_APP_COUNTIES" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"COUNTY_CODE" NUMBER(2,0), 
	"PRIORITY" NUMBER(1,0),
    CONSTRAINT fk_upd_gwis_app_counties_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO"),
    CONSTRAINT fk_upd_gwis_app_counties_county_code FOREIGN KEY (COUNTY_CODE)
        REFERENCES "WSUP"."UPD_GWIS_TL_COUNTIES"("COUNTY_CODE"),
    CONSTRAINT pk_upd_gwis_app_counties PRIMARY KEY(APP_NO, COUNTY_CODE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_APP_COUNTIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_WSP_REGIONS
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_TL_WSP_REGIONS" 
   (	"APP_NO" VARCHAR2(15 BYTE) CONSTRAINT pk_upd_gwis_tl_wsp_regions PRIMARY KEY, 
	"PRIM_PLN_RGN" VARCHAR2(5 BYTE), 
	"PRIM_PERC" NUMBER(38,13), 
	"SEC_PLN_RGN" VARCHAR2(5 BYTE), 
	"SEC_PERC" NUMBER(10,0), 
	"SHAPE_AREA" NUMBER(38,15),
    CONSTRAINT fk_upd_gwis_tl_wsp_regions_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_TL_WSP_REGIONS" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WATER_USE
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WATER_USE" 
   (	"RECORD_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY 
    CONSTRAINT pk_gwis_facility_group PRIMARY KEY,
    "APP_NO" VARCHAR2(15 BYTE), 
	"APPLIES_TO_DATE" DATE, 
	"DATA_VALUE" NUMBER(25,10), 
	"DATA_VALUE_UNITS" VARCHAR2(15 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"REQ_NAME" VARCHAR2(100 BYTE), 
	"REPORT_TYPE" VARCHAR2(10 BYTE), 
	"SITE_ID" VARCHAR2(20 BYTE), 
	"QUALIFIER" VARCHAR2(3 BYTE),
    CONSTRAINT fk_upd_gwis_water_use_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WATER_USE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_ALLOCATION" 
   (	"APP_NO" VARCHAR2(26 BYTE) CONSTRAINT upd_gwis_wu_allocation PRIMARY KEY, 
	"MAX_DAY_ALLOC" NUMBER(38,9), 
	"MAX_MON_ALLOC" NUMBER(38,5), 
	"ANNUAL_ALLOC" NUMBER(38,4),
    CONSTRAINT fk_upd_gwis_wu_allocation FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_ALLOCATION" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_ASSE_BY_SRC
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_APP_ASSE_BY_SRC" 
   (	"RECORD_ID" NUMBER(10,0) CONSTRAINT pk_upd_gwis_wu_app_asse_by_src PRIMARY KEY, 
	"APP_NO" VARCHAR2(15 BYTE), 
	"SOURCE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(128 BYTE), 
	"REC_ANL_ALLOC_BY_SRC" NUMBER(20,2), 
	"REC_FRZ_PROT_BY_SRC" VARCHAR2(26 BYTE), 
	"REC_MAX_DAY_BY_SRC" NUMBER(10,0), 
	"REC_MAX_MON_BY_SRC" NUMBER(10,3), 
	"COMMENTS" VARCHAR2(26 BYTE), 
	"FACGRP_ID" VARCHAR2(26 BYTE), 
	"SR_SEQ_NO" NUMBER(*,0),
    CONSTRAINT fk_upd_gwis_wu_app_asse_by_src_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_APP_ASSE_BY_SRC" TO PUBLIC;
  
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_LU
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_APP_LU" 
   (	"APP_NO" VARCHAR2(20 BYTE),
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"PRIORITY" NUMBER(10,0),
    CONSTRAINT fk_upd_gwis_wu_app_lu_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO"),
    CONSTRAINT fk_upd_gwis_wu_app_lu_landuse_code FOREIGN KEY (LANDUSE_CODE)
        REFERENCES "WSUP"."UPD_GWIS_TL_LAND_USE"("LANDUSE_CODE"),
    CONSTRAINT pk_upd_gwis_wu_app_lu PRIMARY KEY(APP_NO, LANDUSE_CODE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_APP_LU" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_TYPE
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_APP_TYPE" 
   (	"APP_NO" VARCHAR2(15 BYTE) CONSTRAINT pk_upd_gwis_wu_app_type PRIMARY KEY, 
	"FEE_CATEGORY" VARCHAR2(26 BYTE), 
	"FEE_CATEGORY_DESC" VARCHAR2(100 BYTE),
    CONSTRAINT upd_gwis_wu_app_type_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_APP_TYPE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_FACILITIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_FACILITIES" 
   (	"FAC_NAME" VARCHAR2(100 BYTE), 
	"FACGRP_ID" VARCHAR2(15 BYTE), 
	"FACINV_ID" NUMBER(38,0) CONSTRAINT pk_upd_gwis_wu_facilties PRIMARY KEY, 
    "APP_NO" VARCHAR2(20 BYTE),
	"SOURCE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"FACILITY_STATUS" VARCHAR2(1 BYTE), 
	"FACINV_TYPE" VARCHAR2(10 BYTE), 
	"TOP_OF_CASING" NUMBER(10,5), 
	"WELL_DEPTH" NUMBER(20,1), 
	"CASED_DEPTH" NUMBER(20,1), 
	"MEAS_PT_ELEV" NUMBER(20,2), 
	"PUMP_INTAKE_DEPTH" NUMBER(20,2), 
	"PUMP_COORDX" NUMBER(20,11), 
	"PUMP_COORDY" NUMBER(20,10),
    CONSTRAINT fk_upd_gwis_wu_facilities_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO"),
    CONSTRAINT fk_upd_gwis_wu_facilities_source_id FOREIGN KEY (SOURCE_ID)
        REFERENCES "WSUP"."UPD_GWIS_TL_SOURCES"("SOURCE_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_FACILITIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_FACILITY_GROUP
--------------------------------------------------------

  CREATE TABLE "WSUP"."REG_WU_FACILITY_GROUP" 
   (	"FACGRP_ID" NUMBER(10,0) CONSTRAINT pk_reg_wu_facility_group PRIMARY KEY, 
	"APP_NO" VARCHAR2(15 BYTE), 
	"PERMIT_NO" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"PROCESS_TEXT" VARCHAR2(26 BYTE), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	"ACTIVE_FLAG" VARCHAR2(2 BYTE),
    CONSTRAINT fk_reg_wu_facility_group_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."REG_WU_FACILITY_GROUP" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_FAC_GROUP
--------------------------------------------------------

  CREATE TABLE "WSUP"."REG_WU_APP_FAC_GROUP" 
   (	"FACINV_ID" NUMBER(10,0), 
	"FACGRP_ID" NUMBER(10,0), 
	"SEQ_NO" NUMBER(2,0),
    CONSTRAINT fk_reg_wu_app_fac_group_facgrp_id FOREIGN KEY (FACGRP_ID)
        REFERENCES "WSUP"."REG_WU_FACILITY_GROUP" ("FACGRP_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."REG_WU_APP_FAC_GROUP" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_MONITORING
--------------------------------------------------------

  CREATE TABLE "WSUP"."UPD_GWIS_WU_MONITORING" 
   (    "RECORD_ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY 
    CONSTRAINT pk_upd_gwis_wu_monitoring PRIMARY KEY,	
    "APP_NO" VARCHAR2(15), 
	"APPLIES_TO_DATE" DATE, 
	"SITE_ID" VARCHAR2(20), 
	"DATA_TYPE" VARCHAR2(50 BYTE), 
	"DATA_VALUE" NUMBER(20,4), 
	"DATA_VALUE_UNITS" VARCHAR2(50 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"REPORT_TYPE" VARCHAR2(10 BYTE),
    CONSTRAINT fk_upd_gwis_wu_monitoring_app_no FOREIGN KEY (APP_NO)
        REFERENCES "WSUP"."UPD_GWIS_PERMIT_INFO"("APP_NO")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."UPD_GWIS_WU_MONITORING" TO PUBLIC;
  

  