--------------------------------------------------------
--  DDL for Table GWIS_TL_COUNTIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_TL_COUNTIES" 
   (	"COUNTY_CODE" NUMBER(2,0), 
	"COUNTY_NAME" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_TL_COUNTIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_LAND_USE
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_TL_LAND_USE" 
   (	"LANDUSE_CODE" VARCHAR2(10 BYTE), 
	"LANDUSE_DESC" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_TL_LAND_USE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_SOURCES
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_TL_SOURCES" 
   (	"SOURCE_ID" NUMBER(10,0), 
	"SOURCE_TYPE" VARCHAR2(2 BYTE), 
	"SOURCE_NAME" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_TL_SOURCES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_DATA_INDEX
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_DATA_INDEX" 
   (	"GWTID" NUMBER(*,0), 
	"SOURCE_DB" CHAR(5 BYTE), 
	"SITE_ORIGIN" CHAR(9 BYTE), 
	"SITE" VARCHAR2(70 BYTE), 
	"STATION_ORIGIN" CHAR(9 BYTE), 
	"STATION" NVARCHAR2(20), 
	"FAC_NAME" VARCHAR2(100 BYTE), 
	"DATA_TYPE" VARCHAR2(30 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_DATA_INDEX" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_GWTID_INFO
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_GWTID_INFO" 
   (	"GWTID" NUMBER(*,0), 
	"DATA_SOURCE" NUMBER(*,0), 
	"DATA_TYPE" VARCHAR2(10 BYTE), 
	"SITEID_2D" NUMBER(*,0), 
	"SITEID_3D" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_GWTID_INFO" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_SITES_2D
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_SITES_2D" 
   (	"GWTID" NUMBER(*,0), 
	"STATION_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_SITES_2D" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_PERMIT_INFO
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_PERMIT_INFO" 
   (	"PERMIT_NO" VARCHAR2(70 BYTE), 
	"PROJECT_NAME" VARCHAR2(128 BYTE), 
	"APP_NO" VARCHAR2(15 BYTE), 
	"FINAL_ACTION_DATE" DATE, 
	"EXPIRATION_DATE" DATE, 
	"PERMIT_DURATION" VARCHAR2(26 BYTE), 
	"ACRES_SERVED" VARCHAR2(26 BYTE), 
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"FEE_CATEGORY" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_PERMIT_INFO" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_AG_IRR_ACRES
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_AG_IRR_ACRES" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"FIELD_ID" NUMBER(*,0), 
	"IRR_EFF" NUMBER(10,5), 
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"FIELD_ACRES" NUMBER(10,5), 
	"CROP_NAME" VARCHAR2(26 BYTE), 
	"USE_PRIORITY" NUMBER(*,0), 
	"IRR_TYPE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_AG_IRR_ACRES" TO "PUB";
  GRANT READ ON "WSUP"."STG_GWIS_AG_IRR_ACRES" TO "PUB";
  GRANT SELECT ON "WSUP"."STG_GWIS_AG_IRR_ACRES" TO PUBLIC;
  GRANT READ ON "WSUP"."STG_GWIS_AG_IRR_ACRES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_APP_COUNTIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_APP_COUNTIES" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"COUNTY_CODE" NUMBER(2,0), 
	"PRIORITY" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_APP_COUNTIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_TL_WSP_REGIONS
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_TL_WSP_REGIONS" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"PRIM_PLN_RGN" VARCHAR2(5 BYTE), 
	"PRIM_PERC" NUMBER(38,13), 
	"SEC_PLN_RGN" VARCHAR2(5 BYTE), 
	"SEC_PERC" NUMBER(10,0), 
	"SHAPE_AREA" NUMBER(38,15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_TL_WSP_REGIONS" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WATER_USE
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WATER_USE" 
   (	"RECORD_ID" NUMBER(10,0),
    	"APP_NO" VARCHAR2(15 BYTE), 
	"APPLIES_TO_DATE" DATE, 
	"DATA_VALUE" NUMBER(25,10), 
	"DATA_VALUE_UNITS" VARCHAR2(15 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"REQ_NAME" VARCHAR2(100 BYTE), 
	"REPORT_TYPE" VARCHAR2(10 BYTE), 
	"SITE_ID" VARCHAR2(20 BYTE), 
	"QUALIFIER" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WATER_USE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_ALLOCATION
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_ALLOCATION" 
   (	"APP_NO" VARCHAR2(26 BYTE), 
	"MAX_DAY_ALLOC" NUMBER(38,9), 
	"MAX_MON_ALLOC" NUMBER(38,5), 
	"ANNUAL_ALLOC" NUMBER(38,4)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_ALLOCATION" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_ASSE_BY_SRC
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_APP_ASSE_BY_SRC" 
   (	"RECORD_ID" NUMBER(10,0), 
	"APP_NO" VARCHAR2(15 BYTE), 
	"SOURCE_ID" NUMBER(10,0), 
	"NAME" VARCHAR2(128 BYTE), 
	"REC_ANL_ALLOC_BY_SRC" NUMBER(20,2), 
	"REC_FRZ_PROT_BY_SRC" VARCHAR2(26 BYTE), 
	"REC_MAX_DAY_BY_SRC" NUMBER(10,0), 
	"REC_MAX_MON_BY_SRC" NUMBER(10,3), 
	"COMMENTS" VARCHAR2(26 BYTE), 
	"FACGRP_ID" VARCHAR2(26 BYTE), 
	"SR_SEQ_NO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_APP_ASSE_BY_SRC" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_FAC_GROUP
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_WU_APP_FAC_GROUP" 
   (	"FACINV_ID" NUMBER(10,0), 
	"FACGRP_ID" NUMBER(10,0), 
	"SEQ_NO" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_WU_APP_FAC_GROUP" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_LU
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_APP_LU" 
   (	"APP_NO" VARCHAR2(20 BYTE),
	"LANDUSE_CODE" VARCHAR2(5 BYTE), 
	"PRIORITY" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_APP_LU" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_APP_TYPE
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_APP_TYPE" 
   (	"APP_NO" VARCHAR2(15 BYTE), 
	"FEE_CATEGORY" VARCHAR2(26 BYTE), 
	"FEE_CATEGORY_DESC" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_APP_TYPE" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_FACILITIES
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_FACILITIES" 
   (	"FAC_NAME" VARCHAR2(100 BYTE), 
	"FACGRP_ID" VARCHAR2(15 BYTE), 
	"FACINV_ID" NUMBER(38,0), 
    	"APP_NO" VARCHAR2(20 BYTE),
	"SOURCE_ID" NUMBER(*,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"FACILITY_STATUS" VARCHAR2(1 BYTE), 
	"FACINV_TYPE" VARCHAR2(10 BYTE), 
	"TOP_OF_CASING" NUMBER(10,5), 
	"WELL_DEPTH" NUMBER(20,1), 
	"CASED_DEPTH" NUMBER(20,1), 
	"MEAS_PT_ELEV" NUMBER(20,2), 
	"PUMP_INTAKE_DEPTH" NUMBER(20,2), 
	"PUMP_COORDX" NUMBER(20,11), 
	"PUMP_COORDY" NUMBER(20,10)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_FACILITIES" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_FACILITY_GROUP
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_WU_FACILITY_GROUP" 
   (	"RECORD_ID" NUMBER(10,0), 
	"APP_NO" VARCHAR2(15 BYTE), 
	"PERMIT_NO" VARCHAR2(15 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"PROCESS_TEXT" VARCHAR2(26 BYTE), 
	"COMMENTS" VARCHAR2(100 BYTE), 
	"ACTIVE_FLAG" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_WU_FACILITY_GROUP" TO PUBLIC;
  
--------------------------------------------------------
--  DDL for Table GWIS_WU_MONITORING
--------------------------------------------------------

  CREATE TABLE "WSUP"."STG_GWIS_WU_MONITORING" 
   (    "RECORD_ID" NUMBER(10,0),	
    	"APP_NO" VARCHAR2(15), 
	"APPLIES_TO_DATE" DATE, 
	"SITE_ID" VARCHAR2(20), 
	"DATA_TYPE" VARCHAR2(50 BYTE), 
	"DATA_VALUE" NUMBER(20,4), 
	"DATA_VALUE_UNITS" VARCHAR2(50 BYTE), 
	"SUBM_TYPE" NUMBER(*,0), 
	"REPORT_TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  GRANT SELECT ON "WSUP"."STG_GWIS_WU_MONITORING" TO PUBLIC;
  

  