SELECT 
    ADMIN_TABLE.APP_NO,
    gis.FEE_CATEGORY,
    gis.DESCRIPTION as FEE_CATEGORY_DESC
FROM REG.admin_table ADMIN_TABLE
JOIN REG.APP_COUNTIES cnty ON ADMIN_TABLE.APP_NO = cnty.ADMIN_APP_NO
JOIN REG.APP_LANDUSES APP_LANDUSES ON ADMIN_TABLE.APP_NO = APP_LANDUSES.ADMIN_APP_NO
JOIN REG.REG_GIS gis ON ADMIN_TABLE.APP_NO = gis.APP_NO
WHERE cnty.PRIORITY = 1
AND APP_LANDUSES.USE_PRIORITY = 1
AND ADMIN_TABLE.APP_STATUS = 'COMPLETE'
AND APP_LANDUSES.LU_CODE IN ('PWS','NUR','LIV','AQU','AGR','LAN','GOL','REC','IND','COM',
                              'PPG','PPO','PPR','PPM','DIV','DI2')
AND cnty.CNTY_CODE IN {cnty_code}