SELECT
    wu.ID AS FACGRP_ID,
    wu.APP_NO,
    wu.PERMIT_NO,
    wu.NAME,
    wu.PROCESS_TEXT,
    wu.COMMENTS,
    wu.ACTIVE_FLAG
FROM
    WU_FACILITY_GROUP wu
JOIN ADMIN_TABLE admin ON wu.APP_NO = admin.APP_NO
JOIN REG.APP_COUNTIES cnty ON wu.APP_NO = cnty.ADMIN_APP_NO
JOIN REG.APP_LANDUSES APP_LANDUSES ON wu.APP_NO = APP_LANDUSES.ADMIN_APP_NO
WHERE cnty.PRIORITY = 1
AND APP_LANDUSES.USE_PRIORITY = 1
AND admin.APP_STATUS = 'COMPLETE'
AND APP_LANDUSES.LU_CODE IN ('PWS','NUR','LIV','AQU','AGR','LAN','GOL','REC','IND','COM',
                              'PPG','PPO','PPR','PPM','DIV','DI2')
AND cnty.CNTY_CODE IN (6, 8, 11, 13, 22, 26, 28, 36, 43, 44, 47, 48, 49, 50, 53, 56)